# Generated by Django 4.2.16 on 2026-04-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('7_day', '7-Day Follow-Up'), ('30_day', '30-Day Follow-Up')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('scheduled_for', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_surveys', to='approvals.adoptionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_followup_surveys',
                'ordering': ['-scheduled_for'],
                'unique_together': {('adoption', 'survey_type')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.CharField(choices=[('Very well', 'Very well'), ('Moderate', 'Moderate'), ('Struggling', 'Struggling')], max_length=20)),
                ('behavioral_notes', models.TextField(blank=True)),
                ('showing_illness', models.BooleanField(default=False)),
                ('vet_visited', models.BooleanField(default=False)),
                ('satisfied', models.BooleanField(default=True)),
                ('needs_support', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='surveys.followupsurvey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_survey_responses',
            },
        ),
    ]
