# Generated by Django 4.2.16 on 2026-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_surveyresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsurvey',
            name='survey_type',
            field=models.CharField(choices=[('7_day', '7-Day Follow-Up'), ('30_day', '30-Day Follow-Up')], max_length=10),
        ),
    ]
