# Generated by Django 4.2.16 on 2026-04-17 14:26

import apps.surveys.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_followupsurvey_survey_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='survey_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surveys.surveyresponse')),
            ],
            options={
                'db_table': 'django_survey_photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
