# Generated by Django 4.2.16 on 2026-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveyphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='surveyphoto',
            name='image_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyphoto',
            name='mime_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
    ]
