# Generated by Django 4.2.16 on 2026-05-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_surveyphoto_image_surveyphoto_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsurvey',
            name='survey_type',
            field=models.CharField(choices=[('7_day', '7-Day Follow-Up'), ('30_day', '30-Day Follow-Up'), ('90_day', '90-Day Follow-Up')], max_length=10),
        ),
    ]
