# Generated by Django 4.2.16 on 2026-04-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('adoption_approved', 'Adoption Approved'), ('adoption_rejected', 'Adoption Rejected'), ('rehoming_approved', 'Rehoming Approved'), ('rehoming_rejected', 'Rehoming Rejected'), ('survey_scheduled', 'Survey Scheduled'), ('survey_due', 'Survey Due'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
