# Generated by Django 4.2.16 on 2026-04-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehomingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=120)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('duration_owned', models.CharField(blank=True, max_length=30)),
                ('is_vaccinated', models.BooleanField(blank=True, null=True)),
                ('is_neutered', models.BooleanField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('behavior', models.CharField(blank=True, max_length=30)),
                ('behavior_other', models.CharField(blank=True, max_length=100)),
                ('has_aggression', models.BooleanField(blank=True, null=True)),
                ('is_house_trained', models.BooleanField(blank=True, null=True)),
                ('is_leash_trained', models.BooleanField(blank=True, null=True)),
                ('good_with_children', models.BooleanField(blank=True, null=True)),
                ('good_with_pets', models.BooleanField(blank=True, null=True)),
                ('ideal_home_desc', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('details', models.TextField(blank=True)),
                ('tried_alternatives', models.TextField(blank=True)),
                ('can_provide_food', models.BooleanField(default=False)),
                ('can_provide_carrier', models.BooleanField(default=False)),
                ('can_provide_records', models.BooleanField(default=False)),
                ('understands_permanent', models.BooleanField(default=False)),
                ('open_to_followup', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reject_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehoming_decisions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehoming_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_rehoming_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField()),
                ('animal_name', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('reason', models.TextField()),
                ('previous_pet', models.BooleanField(blank=True, null=True)),
                ('previous_pet_details', models.TextField(blank=True)),
                ('primary_caregiver', models.CharField(blank=True, max_length=50)),
                ('housing', models.CharField(blank=True, max_length=50)),
                ('owns_home', models.BooleanField(blank=True, null=True)),
                ('pet_permission', models.BooleanField(blank=True, null=True)),
                ('pet_space', models.CharField(blank=True, max_length=60)),
                ('household_size', models.CharField(blank=True, max_length=20)),
                ('has_children', models.BooleanField(blank=True, null=True)),
                ('children_ages', models.CharField(blank=True, max_length=50)),
                ('has_other_pets', models.BooleanField(blank=True, null=True)),
                ('other_pets_detail', models.CharField(blank=True, max_length=120)),
                ('other_pets_vaccinated', models.BooleanField(blank=True, null=True)),
                ('introduction_plan', models.TextField(blank=True)),
                ('exp', models.CharField(blank=True, max_length=50)),
                ('alone_hours', models.CharField(blank=True, max_length=30)),
                ('backup_care', models.CharField(blank=True, max_length=50)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('vet_plan', models.TextField(blank=True)),
                ('behavior_response', models.CharField(blank=True, max_length=60)),
                ('open_to_guidance', models.BooleanField(blank=True, null=True)),
                ('agree_proper_care', models.BooleanField(default=False)),
                ('agree_long_term', models.BooleanField(default=False)),
                ('agree_no_abandon', models.BooleanField(default=False)),
                ('agree_followup', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reject_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_decisions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_adoption_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
