# Generated by Django 4.2.16 on 2026-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehomingrequest',
            name='last_vacc_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='photo_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='vacc_clinic',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='vacc_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='vacc_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
