# Generated by Django 4.2.16 on 2026-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_rehomingrequest_last_vacc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehomingrequest',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
