# Generated by Django 4.2.16 on 2026-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_rehomingrequest_owner_name_rehomingrequest_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehomingrequest',
            name='last_vacc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehomingrequest',
            name='vacc_clinic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rehomingrequest',
            name='vacc_photos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehomingrequest',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
