# Generated by Django 4.2.16 on 2026-04-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_adoptionrequest_barangay_adoptionrequest_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='region',
        ),
        migrations.RemoveField(
            model_name='rehomingrequest',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='rehomingrequest',
            name='region',
        ),
    ]
