# Generated by Django 4.2.16 on 2026-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_remove_adoptionrequest_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehomingrequest',
            name='found_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='request_type',
            field=models.CharField(choices=[('rehome', 'Rehoming'), ('rescue', 'Rescue / Surrender')], default='rehome', max_length=20),
        ),
    ]
